import type {NextPage} from "next";
import Head from "next/head";
import {Button} from "antd";
import ListSenser from "../components/sensor";
import ChartData from "../components/chart";
import ControlSensor from "../components/sensor/control-sensor";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gite Way 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <h1 className="text-center my-4">Gite Way 1</h1>
        <div className="body-gateway">
          <div className="item-gateway">
            <ListSenser />
            <ChartData />
          </div>
          <ControlSensor />
        </div>
      </div>
    </div>
  );
};

export default Home;
